### ISSUE TITLE
Typo in iproxy.c printf (`connecion` -> `connection`)

### ISSUE THREAD

**Issue by p0358** [libimobiledevice/libusbmuxd#132]
I noticed a small typo in these two lines:

https://github.com/libimobiledevice/libusbmuxd/blob/8d30a559cf0585625d9d05dc8ce0dd495b1de4f4/tools/iproxy.c#L157
https://github.com/libimobiledevice/libusbmuxd/blob/8d30a559cf0585625d9d05dc8ce0dd495b1de4f4/tools/iproxy.c#L160

I figured it might be better to just open an issue for it than PR...

**Comment by nikias** [comment]
Fixed with 30e678d4e76a9f4f8a550c34457dab73909bdd92. Thanks!
