### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [libimobiledevice/libusbmuxd#15]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/libimobiledevice/libusbmuxd/blob/5c7ff87fe9df54e97ae18c9a92138f7b2115c20a/configure.ac#L80)?

**Comment by nikias** [comment]
In master, meanwhile.
