### ISSUE TITLE
Cannot connect to restore mode device

### ISSUE THREAD

**Issue by hazarada** [libimobiledevice/libusbmuxd#16]
I've been porting this code to a visual studio solution, I'm unable to solve this issue however:

When applying a firmware with idevicerestore, its successful up to putting the device in restore mode. Then it goes on to restore_device and restore_open_with_timeout where it subscribes to what I assume is the connect event and then just waits until the attempts are up and fails. 

Meanwhile in libusbmuxd, the device_monitor thread starts, successfully gets the socket from usbmuxd_listen, goes into get_next_event, receive_packet, socket_receive_timeout, socket_check_fd and stops at winsock select function (timeout is 0 so blocks forever).

I triple checked my porting to make sure I didn't introduce any bugs and as far as I can tell I shouldn't have. I'm looking for any tips/advice on how to debug this, thanks.

**Comment by nelson244** [comment]
unable to connect to device

**Comment by piaojin** [comment]
unable to connect to device. device_monitor didn't call.
