### ISSUE TITLE
usbmuxd_get_device_list detecting IPad over wifi

### ISSUE THREAD

**Issue by Polyfun** [libimobiledevice/libusbmuxd#22]
On Windows, usbmuxd_get_device_list is detecting my IPad 1 over wifi, when the IPad is not connected via USB. Is this meant to happen?

The usbmuxd_device_info_t.product_id ==0 when detected over wifi, and the correct product_id when on usb, so a simple fix would be to add a check for di->product_id != 0:

```
got_device_list:

    // explicitly close connection
    UNLOCK;
    socket_close(sfd);

    // create copy of device info entries from collection
    newlist = (usbmuxd_device_info_t*)malloc(sizeof(usbmuxd_device_info_t) * (collection_count(&tmpdevs) + 1));
    dev_cnt = 0;
    FOREACH(usbmuxd_device_info_t *di, &tmpdevs, usbmuxd_device_info_t *) {
        if (di && di->product_id != 0) {
            memcpy(&newlist[dev_cnt], di, sizeof(usbmuxd_device_info_t));
            free(di);
            dev_cnt++;
        }
    } ENDFOREACH
```

**Comment by fishjam** [comment]
After my debug, I found that if call plist_dict_get_item(props, "ConnectionType") in device_record_from_plist(libusbmuxd.c) , then can get the phone connection type, such as "Network" or "USB", so I can try to fix this bug later.

**Comment by fishjam** [comment]
when we try to fix this issue, consider two solutions:
  - 1.simply filter the devices that connected by WiFi.
  - 2.provide user with the additional parameters to filter the device. such as:
```
  idevice_id --list --all   <== list all the devices(USB + Network)
  idevice_id --list --usb <== list usb devices
  idevice_id --list --network <== list network devices.
```

It seems solution 2 is perfect, but the device with USB and network has same  UDID, and idevcie_id and many other tools differentiate device only by UDID.  it can not work, unless change all the tools and user CI scripts.

So consider our ***real demand***, solution 1 is the best.

**Comment by jflow** [comment]
Solution 1 is not the best! Apple has devices out now without a usb port! AppleTV 4k only has network access for this. I need to work with this new usbless device.

**Comment by nikias** [comment]
I'm working on a solution. Stay put.

**Comment by rileytestut** [comment]
Would the solution you're working on allow for interacting with wireless devices? Or just prevent wireless devices showing up as connected? I'm in the same boat, trying to connect to my Apple TV 4K from Linux machine.

**Comment by eni9889** [comment]
@nikias any updates on wireless devices? i.e Apple TV? This is also an issue i'm running into

**Comment by jflow** [comment]
+1 for an update, at least how things are progressing....

**Comment by LittleLydia** [comment]
> I'm working on a solution. Stay put.

@nikias Did the latest version solve this problem?

**Comment by mattijsf** [comment]
@nikias I noticed you mentioned you're working on a proper solution for this issue here: https://github.com/libimobiledevice/libusbmuxd/pull/53#issuecomment-425673643 

Any idea when / how this will land into libusbmuxd and/or libimobiledevice?

**Comment by munchkin09** [comment]
Any updates on this??

**Comment by nikias** [comment]
When using `usbmuxd_get_device_list()` it will include all devices reported back by usbmuxd. You can see how libimobildevice filters out non-USB devices in `idevice_get_device_list()`:

https://github.com/libimobiledevice/libimobiledevice/blob/master/src/idevice.c#L307

You can also use the `usbmuxd_events_subscribe()` (or the older `usbmuxd_subscribe()`) API to subscribe for events. The callback function signature is defined as
```
void callback_function_name(const usbmuxd_event_t *event, void *user_data)
```
By accessing the `event->device` member you can access the `usbmuxd_device_info_t` structure, and then it's `conn_type` member. So basically you can ignore non-USB devices in the callback with a simple
```
if (event->device.conn_type != CONNECTION_TYPE_USB)
    return;
```
