### ISSUE TITLE
(not sure it's a bug, but...) Python-Client (tcprelay.py) missing

### ISSUE THREAD

**Issue by wyatt8740** [libimobiledevice/libusbmuxd#25]
Whatever happened to the python client? Is there a replacement for tcprelay? I used that script HEAVILY. It was incredibly useful!

BTW, using the copy I still had lying around, the latest version of libusbmuxd works with the python script. So why not keep it?

**Comment by FunkyM** [comment]
It was removed due to nobody maintaining it. :)
The iproxy tool should be used instead of the python examples.
Furthermore even iproxy will be superseeded by a new tool in libimobiledevice in the future.

**Comment by wyatt8740** [comment]
alright, so the functionality is still present. What a relief.

**Comment by ishtiaq156** [comment]
@wyatt8740 can you share the release of libusbmuxd with python-client?

**Comment by wyatt8740** [comment]
@ishtiaq156 It's still in the git history... Just checkout a commit from before it was removed. It still works. Alternately tools/iproxy still works for the same purpose in the current releases (though that's a C program). 

    $ git clone https://github.com/libimobiledevice/libusbmuxd.git
    $ cd libusbmuxd
    $ git checkout e866c7136fac5b6a915cb47e3407fb802aa1cba4
