### ISSUE TITLE
Device removed notification arrived when connecting another iPhone

### ISSUE THREAD

**Issue by skortela** [libimobiledevice/libusbmuxd#26]
I have registered to listen device added/removed notifications.
Use case:
Connect iPhone, pair and trust, wait for device is ready.
Connect another iPhone, pair and trust.

When pairing another iPhone, i got notification device removed notification from BOTH devices.
after a while both devices will arrive again.

Note: This happens only on Mac. On Windows there is no extra 'device removed' notifications.

**Comment by nikias** [comment]
Please understand that the device will reconnect via USB when you tap "Trust". This is the intended behavior. I am pretty sure this is what you observe here.

**Comment by skortela** [comment]
I understand that, device is reconnecting, but I have two devices connected
and both are reconnected when trusting the later device.
Should I get reconnect only from later device?



2015-04-16 19:04 GMT+03:00 Nikias Bassen <notifications@github.com>:

**Comment by nikias** [comment]
Hmm indeed you should only get the reconnect for the second device if the first one already reconnected. Also I read you only have this on Mac but not on Windows which is an inconsistent behavior. I will check if I see this on OSX but I don't remember this happening for me.

**Comment by skortela** [comment]
Any update on this?

**Comment by nikias** [comment]
@skortela is this still happening for you? I never really followed up on this.

**Comment by skortela** [comment]
@nikias Could not reproduce.
Now there comes IDEVICE_DEVICE_PAIRED notification once device is paired.
IDEVICE_DEVICE_REMOVE arrives only when USB-cable is removed.
Can be closed.

**Comment by nikias** [comment]
@skortela thanks
