### ISSUE TITLE
/usr/sbin/asr was terminated by signal 11

### ISSUE THREAD

**Issue by Itbnolehurr** [libimobiledevice/libusbmuxd#36]
i am trying to bypass an icloud lock for a friend and idevicrestore.exe keeps stopping at a specific point and tells me that /usr/sbin/asr was terminated by signal 11
ERROR: unable to restore device.

this is the code I use
idevicerestore.exe -u --98583376DB551E9C90029D0580BC64AAB0E2EA46 iPhone3,3_7.1.2_11D257_Restore.ipsw

Here is my cmd session:
Connected to com.apple.mobile.restored, version 13
Device has successfully entered restore mode
Hardware Information:
BoardID: 6
ChipID: 35120
UniqueChipID: 354318619951
ProductionMode: true
Previous restore exit status: 0x100
Partition NAND device (28)
Waiting for NAND (29)
Waiting for NAND (29)
Waiting for device (33)
Checking filesystems (16)
Checking filesystems (16)
Unknown operation (51)
Waiting for NAND (29)
Waiting for NAND (29)
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
About to send filesystem...
Connected to ASR
Validating the filesystem
ERROR: Unable to receive data from ASR
ERROR: Unable to receive validation packet
ERROR: ASR was unable to validate the filesystem
ERROR: Unable to send filesystem
ERROR: Unable to successfully restore device
Got status message
Status: Fail
Log is available:
it peerManager=0xa205c400
start:156
start:156
000096.839452 wlan.N[1] AppleBCMWLANCore::setPowerStateGated():   powerState 1,
fStateFlags 0x20, dev 0x803ab000 (this 1, provider 0)
000096.839496 wlan.N[2] AppleBCMWLANCore::setPowerStateGated():  Received power
state change before driver has initialized, ignoring
AppleSynopsysOTGDevice::gated_handleUSBCableConnect cable connected, but don't h
ave device configuration yet
display-scale = 2
display-rotation = 0
found applelogo at /usr/share/progressui/applelogo@2x.tga
found display: primary
display: 640 x 960
found PTP interface
AppleSynopsysOTGDevice - Configuration: PTP
AppleSynopsysOTGDevice          Interface: PTP
AppleSynopsysOTGDevice - Configuration: iPod USB Interface
AppleSynopsysOTGDevice          Interface: USBAudioControl
AppleSynopsysOTGDevice          Interface: USBAudioStreaming
AppleSynopsysOTGDevice          Interface: IapOverUsbHid
AppleSynopsysOTGDevice - Configuration: PTP + Apple Mobile Device
AppleSynopsysOTGDevice          Interface: PTP
AppleSynopsysOTGDevice          Interface: AppleUSBMux
AppleSynopsysOTGDevice - Configuration: PTP + Apple Mobile Device + Apple USB Et
hernet
AppleSynopsysOTGDevice          Interface: PTP
AppleSynopsysOTGDevice          Interface: AppleUSBMux
AppleSynopsysOTGDevice          Interface: AppleUSBEthernet
AppleSynopsysOTGDevice::gated_registerFunction Register function USBAudioControl

AppleSynopsysOTGDevice::gated_registerFunction Register function USBAudioStreami
ng
IOAccessoryPortUSB::start
AppleSynopsysOTGDevice::gated_registerFunction Register function IapOverUsbHid
virtual bool AppleUSBDeviceMux::start(IOService *) build: Jun 11 2014 20:11:28
init_waste
AppleSynopsysOTGDevice::gated_registerFunction Register function AppleUSBMux
AppleSynopsysOTGDevice::gated_registerFunction Register function AppleUSBEtherne
t
AppleUSBEthernetDevice::start: device-mac-address not found for device in the de
vice-tree, generating a fake one
AppleSynopsysOTGDevice::gated_registerFunction Register function PTP
AppleSynopsysOTGDevice::startUSBStack Starting usb stack
IOReturn AppleUSBDeviceMux::setPropertiesGated(OSObject *) setting debug level t
o 7
AppleUSBDeviceMux::handleConnectResult new session 0xa364f840 established 62078<
-lo0->49152 62078<-usb->26112
void AppleUSBDeviceMux::handleMuxTCPInput(mbuf_t) received reset, closing 0xa364
f840
recv(13, 4) failed: connection closed
unable to read message size: -1
could not receive message
AppleUSBDeviceMux::handleConnectResult new session 0xa364f840 established 62078<
-lo0->49153 62078<-usb->26368
AppleUSBDeviceMux::sessionUpcall socket is closed, session 0xa364f840 (62078<-lo
0->49153 62078<-usb->26368)
AppleUSBDeviceMux::handleConnectResult new session 0xa364f840 established 62078<
-lo0->49154 62078<-usb->26624
client protocol version 13
*** UUID 256172B6-0663-3AC5-C19D-A8F171E4D268 ***
Restore options:
        UUID                           => <CFString 0x15577cb0 [0x3b3ae0]>{conte
nts = "256172B6-0663-3AC5-C19D-A8F171E4D268"}
        MinimumSystemPartition         => <CFNumber 0x15577c00 [0x3b3ae0]>{value
 = +1522, type = kCFNumberSInt64Type}
        SystemPartitionSize            => <CFNumber 0x15579040 [0x3b3ae0]>{value
 = +1522, type = kCFNumberSInt64Type}
        PersonalizedDuringPreflight    => <CFBoolean 0x3b3e90 [0x3b3ae0]>{value
= true}
        SystemPartitionPadding         => <CFBasicHash 0x15577ce0 [0x3b3ae0]>{ty
pe = mutable dict, count = 5,
entries =>
        2 : <CFString 0x15577c30 [0x3b3ae0]>{contents = "128"} = <CFNumber 0x155
77c60 [0x3b3ae0]>{value = +1280, type = kCFNumberSInt64Type}
        3 : <CFString 0x15577d10 [0x3b3ae0]>{contents = "16"} = <CFNumber 0x1557
8cc0 [0x3b3ae0]>{value = +160, type = kCFNumberSInt64Type}
        4 : <CFString 0x15578cd0 [0x3b3ae0]>{contents = "32"} = <CFNumber 0x1557
8c00 [0x3b3ae0]>{value = +320, type = kCFNumberSInt64Type}
        5 : <CFString 0x15578b00 [0x3b3ae0]>{contents = "8"} = <CFNumber 0x15579
190 [0x3b3ae0]>{value = +80, type = kCFNumberSInt64Type}
        8 : <CFString 0x15578bb0 [0x3b3ae0]>{contents = "64"} = <CFNumber 0x1557
8af0 [0x3b3ae0]>{value = +640, type = kCFNumberSInt64Type}
}

entering load_sep_os
device has no sep
entering partition_nand_device
device supports boot-from-NAND
nand device is already partitioned
entering wait_for_storage_device
Searching for NAND service
Found NAND service: IOFlashStoragePartition
NAND initialized. Waiting for devnode.
entering clear_remap_variable
executing /usr/sbin/nvram
entering format_effaceable_storage
effaceable storage is formatted, nothing to do
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2
executing /sbin/fsck_hfs
** /dev/rdisk0s1s1
   Executing fsck_hfs (version hfs-277.10.5).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
entering check_for_restore_log
restore log does not exist
entering unmount_filesystems
error unmounting '/mnt2': Invalid argument
entering clean_NAND
entering format_storage_for_LwVM
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2
entering check_for_suspicious_partitions
executing /sbin/fsck_hfs
** /dev/rdisk0s1s2
   Executing fsck_hfs (version hfs-277.10.5).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
executing /sbin/mount_hfs
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt1
ramrod_roll_media_keys: data_partition = /dev/disk0s1s2
ramrod_roll_media_keys: storage_media = /dev/disk0s1
ramrod_roll_media_keys: data_partition_name = disk0s1s2
ramrod_roll_media_keys: data_partition_uuid = 285AA8B1-8DDB-4A73-9875-9B01FD3802
0F
executing /usr/sbin/nvram
entering mount_filesystems
executing /sbin/fsck_hfs
** /dev/rdisk0s1s1
   Executing fsck_hfs (version hfs-277.10.5).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
executing /sbin/fsck_hfs
** /dev/rdisk0s1s2
   Executing fsck_hfs (version hfs-277.10.5).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
executing /sbin/mount_hfs
LwVM::gptUUIDExists - UUID already rekeyed
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt2
entering resize_system_partition_to_options
User specified system partition size, skipping firmware extras size.
Found SystemPartitionPadding value of 83886080 bytes
Erasing system partition prior to resize operation.
block size for /dev/disk0s1s1: 8192
/sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s1
executing /sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/d
isk0s1s1
Initialized /dev/rdisk0s1s1 as a 2 GB case-sensitive HFS Plus volume with a 8192
k journal
executing /sbin/fsck_hfs
** /dev/rdisk0s1s1
   Executing fsck_hfs (version hfs-277.10.5).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
Trying to resize system partition to 1679818752 bytes aka 1602 MB
entering adjust_partition_preflight
partition:0 requiredSize=205056
no change in size
Successfully resized the system partition
entering maximize_data_partition
entering adjust_partition_preflight
partition:1 requiredSize=2251799813685248
maximizing data partition to 6289358847 bytes
entering adjust_partition_preflight
partition:1 requiredSize=767744
no change in size
Successfully resized data partition to consume free blocks
The system partition now has a total HFS+ capacity of 1602 MB
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2
entering unmount_filesystems
entering ramrod_ticket_update
looking up root ticket hash
device tree ticket-hash: <CFData 0x1557a500 [0x3b3ae0]>{length = 20, capacity =
20, bytes = 0x611a3db4b619688ff9936b18ac7387617eb792ad}
ticket_hash: 611A3DB4B619688FF9936B18AC7387617EB792AD
received valid ticket (2741 bytes)
entering restore_images
Successfully marked device node /dev/rdisk0s1s1 as static data
executing /usr/sbin/asr -source asr://localhost:12345 -target /dev/disk0s1s1 -er
ase -noprompt --chunkchecksum --puppetstrings
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t)
 new session to port 12345 failed: 61
ASR: asr: Unable to disable idle sleep - -536870199
ASR STATUS: start       241.1   multicast-client
ASR: Waiting for connection attempt from server
AppleUSBDeviceMux::handleConnectResult new session 0xa364f370 established 12345<
-lo0->49156 12345<-usb->27136
ASR STATUS: setup
ASR: Validating target...
ASR: done
ASR STATUS: metadata
ASR: Validating source...
ASR: (null)
/usr/sbin/asr was terminated by signal 11
AppleUSBDeviceMux::sessionUpcall socket is closed, session 0xa364f370 (12345<-lo
0->49156 12345<-usb->27136)

ERROR: Unable to restore device

 anyway to fix this?

**Comment by minhlmo** [comment]
nts = "13994007-DD55-C990-624E-E6C0175404BE"}
        MinimumSystemPartition         => <CFNumber 0x176284a0 [0xa64468]>{value
 = +2033, type = kCFNumberSInt64Type}
        SystemPartitionSize            => <CFNumber 0x17628120 [0xa64468]>{value
 = +2033, type = kCFNumberSInt64Type}
        PersonalizedDuringPreflight    => <CFBoolean 0xa6474c [0xa64468]>{value
= true}
        SystemPartitionPadding         => <CFBasicHash 0x17628280 [0xa64468]>{ty
pe = mutable dict, count = 9,
entries =>
        0 : <CFString 0x17627db0 [0xa64468]>{contents = "512"} = <CFNumber 0x176
27f40 [0xa64468]>{value = +1280, type = kCFNumberSInt64Type}
        2 : <CFString 0x176284f0 [0xa64468]>{contents = "128"} = <CFNumber 0x176
27af0 [0xa64468]>{value = +1280, type = kCFNumberSInt64Type}
        3 : <CFString 0x17627b00 [0xa64468]>{contents = "16"} = <CFNumber 0x1762
8170 [0xa64468]>{value = +160, type = kCFNumberSInt64Type}
        4 : <CFString 0x17627f80 [0xa64468]>{contents = "32"} = <CFNumber 0x1762
7da0 [0xa64468]>{value = +320, type = kCFNumberSInt64Type}
        5 : <CFString 0x17627de0 [0xa64468]>{contents = "768"} = <CFNumber 0x176
27df0 [0xa64468]>{value = +1280, type = kCFNumberSInt64Type}
        6 : <CFString 0xa37348 [0xa64468]>{contents = "8"} = <CFNumber 0x17627c9
0 [0xa64468]>{value = +80, type = kCFNumberSInt64Type}
        7 : <CFString 0x17628590 [0xa64468]>{contents = "1024"} = <CFNumber 0x17
6284d0 [0xa64468]>{value = +1280, type = kCFNumberSInt64Type}
        8 : <CFStri...
entering load_sep_os
device has no sep
entering ramrod_ticket_update
looking up root ticket hash
crypto-hash-method not found, defaulting to SHA1
device tree ticket_hash: 342423C823185136760278538023C72F2F5E2A5B
computed ticket_hash   : 342423C823185136760278538023C72F2F5E2A5B
received valid ticket (2732 bytes)
entering partition_nand_device
device supports boot-from-NAND
nand device is already partitioned
entering wait_for_storage_device
Searching for NAND service
Found NAND service: IOFlashStoragePartition
NAND initialized. Waiting for devnode.
entering clear_remap_variable
executing /usr/sbin/nvram
entering ramrod_reprobe_device_path
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
entering ramrod_reprobe_device_path
unable to stat block device /dev/disk1: No such file or directory
/dev/disk1 does not exist, skipping
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s1) returned 0
** /dev/rdisk0s1s1
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2019 cacheSize=64608K.
   Executing fsck_hfs (version hfs-305.1.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
AMSupportPlatformCreateBufferFromNativeFilePath: open failed: No such file or di
rectory
__getFDRSealingMap_block_invoke: Could not load sealing map from '/usr/lib/FDRSe
alingMap.plist'
AMFDRSealingMapGetEntriesForDevice: Could not load sealing map
restored_fdr_initialize returned false
RestoredFDRCreate() returned 0
FDR is not supported on this device
RestoredFDRSaveData: restoredFDR is NULL, not able to preserve FDR data.
RestoredFDRSaveData success
entering check_for_restore_log
restore log does not exist
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s2) returned 0
** /dev/rdisk0s1s2
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2019 cacheSize=64608K.
   Executing fsck_hfs (version hfs-305.1.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt2
entering dump_panic_logs
executing /System/Library/CoreServices/DumpPanic
entering check_for_ota_logs_with_mount_point
Not preserving OTA logs for update install
restore log does not exist
skipping log submission, failed to read user settings from: /mnt2/mobile/Library
/ConfigurationProfiles/EffectiveUserSettings.plist
Diagnostic log submission disabled
Searching /mnt2/mobile/Library/Logs/CrashReporter/
check_for_ota_logs_with_mount_point complete
Successfully checked for OTA logs
submit_update_stats: mounting data partition for update install
executing /sbin/fsck_hfs
ERROR: volume /mnt2 is mounted with write access. Re-run with (-l) to freeze vol
ume.
fsck failed on /dev/disk0s1s2
entering unmount_filesystems
create_baseband_update_options: Got imeisv: 21
baseband updater options = <CFBasicHash 0x1752da30 [0xa64468]>{type = mutable di
ct, count = 4,
entries =>
        0 : <CFString 0x139f72c [0xa64468]>{contents = "IMEISwVersion"} = <CFNum
ber 0x17629480 [0xa64468]>{value = +21, type = kCFNumberSInt32Type}
        2 : <CFString 0x139f7bc [0xa64468]>{contents = "autoSetupEnv"} = <CFBool
ean 0xa64754 [0xa64468]>{value = false}
        3 : <CFString 0x139f70c [0xa64468]>{contents = "restoredInternal"} = <CF
Boolean 0xa64754 [0xa64468]>{value = false}
        5 : <CFString 0x139f7cc [0xa64468]>{contents = "disablePing"} = <CFBoole
an 0xa6474c [0xa64468]>{value = true}
}

_baseband_update_requires_filesystems_once: querying baseband to determine if it
 requires system filesystem
bbupdater: cmdCopyRequirePartitionMount: supports flashless 1

bbupdater: cmdCopyRequirePartitionMount: supports REFS 0

bbupdater: cmdCopyRequirePartitionMount: need data partition for coredumps

_baseband_update_requires_filesystems_once: query returned <CFBasicHash 0x176295
60 [0xa64468]>{type = mutable dict, count = 3,
entries =>
        0 : <CFString 0x139f3ec [0xa64468]>{contents = "requireSystemPartitionMo
unt"} = <CFBoolean 0xa6474c [0xa64468]>{value = true}
        1 : <CFString 0x139f40c [0xa64468]>{contents = "requireUserPartitionMoun
t"} = <CFBoolean 0xa6474c [0xa64468]>{value = true}
        2 : <CFString 0x139f41c [0xa64468]>{contents = "requestedBasebandFSParti
tionMountSize"} = <CFNumber 0x176247c0 [0xa64468]>{value = +0, type = kCFNumberS
Int32Type}
}

entering clean_NAND
entering format_effaceable_storage
effaceable storage is formatted, nothing to do
entering format_storage_for_LwVM
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
ramrod_roll_media_keys: data_partition = /dev/disk0s1s2
ramrod_roll_media_keys: storage_media = /dev/disk0s1
ramrod_roll_media_keys: data_partition_name = disk0s1s2
ramrod_roll_media_keys: data_partition_uuid = 88118F3E-B233-4931-9027-0E3E07B3D9
02
SYSLOG: Oct  8 05:38:36 localhost kernel[0] <Notice>: LwVM::gptUUIDExists - UUID
 already rekeyed
executing /usr/sbin/nvram
entering mount_filesystems
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s1) returned 0
** /dev/rdisk0s1s1
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2019 cacheSize=64608K.
   Executing fsck_hfs (version hfs-305.1.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s2) returned 0
** /dev/rdisk0s1s2
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2019 cacheSize=64608K.
   Executing fsck_hfs (version hfs-305.1.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt2
entering resize_system_partition_to_options
User specified system partition size, skipping firmware extras size.
Found SystemPartitionPadding value of 167772160 bytes
Erasing system partition prior to resize operation.
block size for /dev/disk0s1s1: 4096
/sbin/newfs_hfs -s -v System -J /dev/disk0s1s1
executing /sbin/newfs_hfs -s -v System -J /dev/disk0s1s1
Initialized /dev/rdisk0s1s1 as a 2 GB case-sensitive HFS Plus volume with a 8192
k journal
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s1) returned 0
** /dev/rdisk0s1s1
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2019 cacheSize=64608K.
   Executing fsck_hfs (version hfs-305.1.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
Trying to resize system partition to 2299527168 bytes aka 2193 MB
entering adjust_partition_preflight
partition:0 requiredSize=561408
no change in size
Successfully resized the system partition
entering maximize_data_partition
entering adjust_partition_preflight
partition:1 requiredSize=4503599627370496
maximizing data partition to 13554941951 bytes
entering adjust_partition_preflight
partition:1 requiredSize=3309312
no change in size
Successfully resized data partition to consume free blocks
The system partition now has a total HFS+ capacity of 2193 MB
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
entering unmount_filesystems
entering restore_images
Successfully marked device node /dev/rdisk0s1s1 as static data
executing /usr/sbin/asr -source asr://localhost:12345 -target /dev/disk0s1s1 -er
ase -noprompt --chunkchecksum --puppetstrings
SYSLOG: Oct  8 05:38:42 localhost kernel[0] <Notice>: void AppleUSBDeviceMux::ha
ndleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 12345
 failed: 61
SYSLOG: Oct  8 05:38:42 localhost asr[28] <Error>: bootstrap_look_up2 failed wit
h 0x44e
ASR: asr: Unable to disable idle sleep - -536870199
ASR STATUS: start       242.6   multicast-client
ASR: Waiting for connection attempt from server
SYSLOG: Oct  8 05:38:42 localhost asr[28] <Error>: __net_helper_get_connection_b
lock_invoke_3 could not connect to networkd
ASR STATUS: setup
ASR: Validating target...
ASR: done
ASR STATUS: metadata
ASR: Validating source...
ASR: (null)
/usr/sbin/asr was terminated by signal 11

ERROR: Unable to restore device

C:\libi>

**Comment by minhlmo** [comment]
ios 9.0.1 are dark. I tried the 6.1.3, dark do not ram dicsk and BuildManifest.plist and renamed to load mode. sorry my english is not good
mail: minhmlon@gmail.com
