### ISSUE TITLE
Read/Write between Mac and iPhone using libusbmuxd

### ISSUE THREAD

**Issue by pf2707** [libimobiledevice/libusbmuxd#37]
I current use libimobiledevice to work around Mac and iPhone. libusbmuxd is very helpful to get device (iPhone/iPad) information when connects to Mac app through USB. 

I want more, I want to read/write data (a file like document, image, video, ...) from Mac to iPhone and vice versa but I can't get any document or tutorial on the Internet guiding how to do it.

Can anyone help me

**Comment by mexmer** [comment]
such interaction is not supported by iOS.
if application supports Document Sharing feature, you can use it to transfer files from/to application sandbox, but that's as much, as you can do.
