### ISSUE TITLE
Problems with libusbmuxd-dev

### ISSUE THREAD

**Issue by OsukaS** [libimobiledevice/libusbmuxd#47]
hi, i really need help with this problem, i try to build imobiledevice, but ubuntu says that libusbmuxd isn't the lastest version, i try to download libusbmuxd from libimobiledevice.org, but i don't know how can a make it works, if some one can help me :( 
![captura de pantalla de 2017-04-08 04 11 02](https://cloud.githubusercontent.com/assets/26902443/24827575/14f4702e-1c12-11e7-8683-8ee9a563b53e.png)

**Comment by uberhitzt** [comment]
Hi. What you posted above is not an issue pertaining to the operation of **libusbmuxd**, so you are looking for help in the wrong place. It appears that the version of **libusbmuxd** installed on your computer is too old for building **libimobiledevice**. Therefore, your starting point should be determining how to upgrade the existing version of **libusbmuxd** for your host operating system. You could do this in several ways, but these are typical: 

1. Use the package manager (e.g. apt-get install libusbmuxd-dev) to fetch the latest version distributed by your host operating system. Note that the version will be older than the code published here

2. Download the source code from github and compile it on your target operating system. 

If you have trouble doing either of these, search the web. There are several blogs and forum posts describing how to build and install **libimobiledevice** on Ubuntu. In fact, [this blog post](https://ashnvishy.wordpress.com/2016/02/10/installing-libimobiledevice-on-ubuntu-14-04-trusty/) describes the situation you posted above.
