### ISSUE TITLE
Getting Segmentation Fault

### ISSUE THREAD

**Issue by indianajorge** [libimobiledevice/libusbmuxd#63]
Hi, in

@libusbmuxd.c
Line 270:
```
	if (!devinfo->udid[0]) {
		LIBUSBMUXD_ERROR("%s: Failed to get SerialNumber (UDID)!\n", __func__);
		free(devinfo);
		devinfo = NULL;
	}
	if (!devinfo->conn_type) {
		...
```
Shouldn't this sequence of conditions be in a if/else structure?  if we set devinfo to NULL in the first condition we'll most probably obtain a Segmentation fault in the second.
thank you

**Comment by nikias** [comment]
Good catch. Let me fix that.
