### ISSUE TITLE
Question about usbmuxd_connect

### ISSUE THREAD

**Issue by histronger** [libimobiledevice/libusbmuxd#69]
Hello guys, I encounter a problem when connecting an iOS device using USB wire, which is caused by the return value of the function usbmuxd_connect. So I'm writing to ask in what circumstance does the function retrun a negtive value? BTW, where can I get the implementation of this function? Thanks for your help!
`int usbmuxd_connect(const int handle, const unsigned short tcp_port);`

**Comment by nikias** [comment]
A negative value means it failed to connect, obviously. Implementation is here: https://github.com/libimobiledevice/libusbmuxd/blob/master/src/libusbmuxd.c#L1508
The negative return values are negative errno error codes.
