### ISSUE TITLE
Win32-libusbmuxd unresolved symbols

### ISSUE THREAD

**Issue by krisanovdev** [libimobiledevice/libusbmuxd#70]
I've got next linker errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _mutex_init	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _thread_free	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _mutex_unlock	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _thread_join	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _thread_new	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _thread_cancel	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _mutex_lock	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _thread_once	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1	
Error	LNK2001	unresolved external symbol _thread_alive	usbmuxd	D:\imobile\libusbmuxd\libusbmuxd.obj	1

**Comment by MrKris99** [comment]
I guess that we need to add thread.c and thread.h from common folder to usbmuxd.cxproj project.

**Comment by MrKris99** [comment]
Anyone?
