### ISSUE TITLE
usbmuxd_recv_timeout blocks thread forever

### ISSUE THREAD

**Issue by MrKris99** [libimobiledevice/libusbmuxd#75]
Subject.
Reproduced on MacOS 10.13 with iPhone 6s iOS 11.4.1

**Comment by nikias** [comment]
Not really helpful, can you provide sample code or commands that you executed so I can reproduce it?

**Comment by MrKris99** [comment]
Sorry, I'll give you example around 25.08 - have no time right now.

**Comment by nikias** [comment]
any update on this?

**Comment by MrKris99** [comment]
Cannot reproduce on last libubmuxd.
