### ISSUE TITLE
iproxy <local_port> <device_port> command stuck on 'waiting for connection' line

### ISSUE THREAD

**Issue by artemryazantsev** [libimobiledevice/libusbmuxd#76]
Environment:
- Latest usbmuxd/libimobiledevice/iproxy libraries
- iOS devices (tested on ios 11, ios 12.3) connected via USB
- Latest Mac OS Mojave / Macbook Pro 

**After execution of regular iproxy command it stucks on 'Waiting for connection' line.**

the example is `iproxy 9911 2888 <device_ud>`

Is there anything I missed in manuals? 

Just need to forward traffic from device to machine (from device port 2888)

Thanks in advance

**Comment by MrKris99** [comment]
It's okay. iProxy is just foreground process. Please open another terminal and do what you want to do.

**Comment by artemryazantsev** [comment]
thank you it works
