### ISSUE TITLE
Realtime protocols with libusbmuxd?

### ISSUE THREAD

**Issue by kakyoism** [libimobiledevice/libusbmuxd#77]
Correct me if I'm wrong, please: Realtime data requires UDP-based protocols like RTP. But no UDP is mentioned in documentation of  usbmuxd. So is it because USB is a guaranteed realtime channel that TCP / UDP is not an issue? 

If that were true, then how should I make an existing realtime protocol such as RTP work with TCP?

**Comment by nikias** [comment]
Only TCP works over usbmux.

**Comment by nikias** [comment]
Closing. Out of scope of this project.
