### ISSUE TITLE
Buffers limit transfer speed

### ISSUE THREAD

**Issue by cbrx-fw** [libimobiledevice/libusbmuxd#78]
Increase the size of the send and receive buffers to improve performance of the network connections. Please see the attached patch. This was found when testing with Cambrionix ThunderSync2-16 and idevicerestore and achieved a speedup that halved the time taken to restore 16 iPads.
[idev_sock_bufsize.txt](https://github.com/libimobiledevice/libusbmuxd/files/3615907/idev_sock_bufsize.txt)

**Comment by nikias** [comment]
Nice. I already have this in git: https://github.com/libimobiledevice/libusbmuxd/blob/master/common/socket.c#L144-L150 maybe you are looking at an older source version?

**Comment by cbrx-fw** [comment]
Nice. I already have this in git: https://github.com/libimobiledevice/libusbmuxd/blob/master/common/socket.c#L144-L150 maybe you are looking at an older source version?



Yes, so you do, sorry for the noise. That’s great.

Thanks,

Andrew

**Comment by nikias** [comment]
No worries! Thanks for the feedback :)
