### ISSUE TITLE
iproxy command does not write data to stdout

### ISSUE THREAD

**Issue by vinodvpatil** [libimobiledevice/libusbmuxd#79]
while i am trying to capture some events through stdout data for example "waiting for connection 
" I see string is not written into stdout. 

This issue I am seeing in Mac OS, is there any way i can do some changes in Mac OS config ?

**Comment by nikias** [comment]
You probably want to use the inetcat tool.

**Comment by nikias** [comment]
`waiting for connection` is definitely printed on stdout, and this works on macOS and Linux for sure.
