### ISSUE TITLE
Crash on iphone plugin

### ISSUE THREAD

**Issue by embyte0** [libimobiledevice/libusbmuxd#83]
Hi,

I am observing a crash when I connect my iphone to my debian testing. All packages are up to date. 

Nov 20 10:29:23 host upowerd[5467]: *** stack smashing detected ***: <unknown> terminated
Nov 20 10:29:23 host systemd[1]: upower.service: Main process exited, code=killed, status=6/ABRT
Nov 20 10:29:23 host systemd[1]: upower.service: Failed with result 'signal'.
Nov 20 10:29:23 host systemd[1]: upower.service: Service RestartSec=100ms expired, scheduling restart.
Nov 20 10:29:23 host systemd[1]: upower.service: Scheduled restart job, restart counter is at 51.
Nov 20 10:29:23 host systemd[1]: Stopped Daemon for power management.
Nov 20 10:29:23 host systemd[1]: Starting Daemon for power management...

Thanks

**Comment by nikias** [comment]
Caused by outdated packages, but libusbmuxd is not the reason.
