### ISSUE TITLE
icat: collides with sleuthkit

### ISSUE THREAD

**Issue by blshkv** [libimobiledevice/libusbmuxd#84]
both libusbmuxd and sleuthkit install icat binary into /usr/bin. That makes it harder to maintain the tool.
It also might break other tools which call "/usr/bin/icat".

Please change the name to something more unique. I think ```inetcat``` will do it.

**Comment by nikias** [comment]
I can't really think about a better name especially now that it's in use already...
@aguinet what do you think about 'muxcat'?

**Comment by aguinet** [comment]
I'm fine with both `inetcat` or `muxcat`. `idevcat` could also be a solution!

**Comment by nikias** [comment]
Oh I didn't see the inetcat suggestion. I think that's probably the name to go with. Let me make a poll on twitter.

**Comment by aguinet** [comment]
BTW, the suggested patch does not seem correct to me. It supposes libusbmuxd is installed in `/usr` (which might not always be the case), and would erase a potentially already existing `icat` binary.

The proper patch IMHO is just to rename the name of the tool within the source code!

**Comment by nikias** [comment]
Done: 2b452316ccdab081cd6add860d6f0eaab46c4879 tag 2.0.1

**Comment by nikias** [comment]
Sorry, made a mistake, new commit is e97cebeaf7d8f3793b40c3e7bb3ab63853098f5d.
