### ISSUE TITLE
On Windows, do we need iTunes to use imobiledevice?

### ISSUE THREAD

**Issue by kakyoism** [libimobiledevice/libusbmuxd#86]
Looks like imobiledevice depends on iTunes Windows to start the Apple services for usbmuxd, but correct me if I'm wrong:

Isn't usbmuxd an open source version of the usbmux so it probably already includes all the dependencies in its implementation? 

Or is it that it just does not support Windows?

**Comment by mexmer** [comment]
usbmuxd is indeed opensource, but i'm not aware, that it does work properly on windows. there is no udev or similar system and direct access to hardware is much more complicated, it will need implement ioctl or other communication framework for communicating with devices on windows. 

so if you want to use libimobiledevice on windows, then your best bet is using itunes (and their mux service)
