### ISSUE TITLE
Depend on libplist 2.0.0 instead of 2.1.0

### ISSUE THREAD

**Issue by guyru** [libimobiledevice/libusbmuxd#90]
Hi,

configure.ac requires libplist >= 2.1.0. It seems libusbmuxd compiles fine against libplist 2.0.1. Can we change configure.ac to reflect less strict dependency? It would help with Debian Buster as it has libplist 2.0.1.

**Comment by nikias** [comment]
Hi, Debian Buster should adopt 2.1.0 as a security update, from 2.0.0 to 2.1.0 there were several bug/security fixes (for example UaF) that should be reason enough to provide an updated package.
We are in the process right now getting PROPER releases done for all of the libraries. Libplist will be released as 2.2.0 hopefully later today.
